NDefines.NMilitary.COMBAT_OVER_WIDTH_PENALTY = -1
NDefines.NMilitary.COMBAT_OVER_WIDTH_PENALTY_MAX = -0.33
NDefines.NMilitary.BASE_COMBAT_WIDTH = 96
NDefines.NMilitary.ADDITIONAL_COMBAT_WIDTH = 48
NDefines.NProduction.DEFAULT_MAX_NAV_FACTORIES_PER_LINE = 25
NDefines.NProduction.CONVOY_MAX_NAV_FACTORIES_PER_LINE = 25
NDefines.NProduction.CAPITAL_SHIP_MAX_NAV_FACTORIES_PER_LINE = 15
